"""
Shared Market Protocols
=======================
"""

from __future__ import annotations

from datetime import datetime
from typing import Callable, Optional, Protocol, runtime_checkable

from core.shared.markets.models import MarketEvent, Outcome


@runtime_checkable
class RegistryProtocol(Protocol):
    async def start(self) -> None: ...
    async def stop(self) -> None: ...

    def get_all_events(self) -> list[MarketEvent]: ...
    def get_tradeable_events(self) -> list[MarketEvent]: ...
    def get_event(self, event_id: str) -> Optional[MarketEvent]: ...
    def get_event_by_token(self, token_id: str) -> Optional[tuple[MarketEvent, Outcome]]: ...
    def get_all_token_ids(self) -> list[str]: ...
    def get_stats(self) -> dict: ...


@runtime_checkable
class BBATrackerProtocol(Protocol):
    ws_connected: bool
    last_ws_message_at: Optional[datetime]

    async def start(self) -> None: ...
    async def stop(self) -> None: ...
    async def fetch_all_prices(self, event: MarketEvent) -> dict: ...
    def get_gamma_only_tokens(self) -> list[str]: ...
    def get_stats(self) -> dict: ...


@runtime_checkable
class TrackerFactoryProtocol(Protocol):
    def __call__(
        self,
        on_price_update: Callable[[str, str], None],
        token_filter: Optional[Callable[[], list[str]]] = None,
    ) -> BBATrackerProtocol: ...
